// STREETMOOD Products - Main product list
// This file contains all products for STREETMOOD catalog
if (typeof products === 'undefined') {
    var products = [
        {id: 1, name: "Air Jordan 10 - White brown40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 2, name: "Air Jordan 10 - White black40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 3, name: "Air Jordan 10 - White black red40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 4, name: "Air Jordan 10 - White black grass green40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 5, name: "Air Jordan 10 - shadow40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 6, name: "Air Jordan 10 - owl40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 7, name: "Air Jordan 10 - New white black40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 8, name: "Air Jordan 10 - Miami Super Bowl40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 9, name: "Air Jordan 10 - mandarin duck40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 10, name: "Air Jordan 10 - grey cement40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 11, name: "Air Jordan 10 - Chicago40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 12, name: "Air Jordan 10 - bull40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 13, name: "Air Jordan 10 - black white red40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 14, name: "Air Jordan 10 - black white blue40-47", size: "40-47", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 15, name: "Air Jordan 4 Retro white orchid36-40", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 16, name: "Air Jordan 4 Retro particle dark blue40-46", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 17, name: "Air Jordan 4 Retro particle beige40-46", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 18, name: "Air Jordan 4 Retro granular moonlight40-46", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 19, name: "Air Jordan 4 Retro denim40-46", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 20, name: "Air Jordan 4 Retro black-white36-46", size: "36-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 21, name: "Air Jordan 4 Retro black particle40-46", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 22, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 23, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 24, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 25, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 26, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 27, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 28, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 29, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 30, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 31, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 32, name: "Air Jordan 4 Low", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 33, name: "Air Jordans 1 Mid 'Black Gold'", size: "36-40", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 34, name: "Air Jordans 1 High 'Hyper Royal' 555088-402", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 35, name: "Air Jordans 1 Retro High OG 'Black White' 555088-168", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 36, name: "Air Jordans 1 High University Blue 555088-134", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 37, name: "Air Jordans 1 CD4487-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 38, name: "Air Jordans 1 Retro High CN8607-002", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 39, name: "Wmns Air Jordans 1 Mid \"Guava Ice\" BQ6472-800", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 40, name: "Air Jordans 1 Retro High OG \"Obsidian/University Blue\" 555088-140", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 41, name: "Air Jordans 1 Retro High OG'Mocha' 555088-105", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 42, name: "Air Jordans 1 High Black Smoke Grey 555088-03", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 43, name: "Air Jordans 1 High \"UNC\" AQ0818-148", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 44, name: "Air Jordans 1 MID SE GS \"Grey Camo Swoosh\" DC9035-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 45, name: "Air Jordans 1 Retro High OG Rust Pink Q6472-800", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 46, name: "Air Jordans 1 Retro High OG 'Shadow' 555088-013", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 47, name: "Air Jordan 1 Retro High OG GS \"Court Purple 2.0\" 575441-555088-500", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 48, name: "Air Jordans 1 Retro High Co.JP 'Midnight Navy' DC1788-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 49, name: "Air Jordans 1 Mid \"Chicago Black Toe\" 554724-069", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 50, name: "Air Jordans 1 High 'Light Smoke Grey'", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 51, name: "Air Jordans 1 Retro High OG SE \"Satin\" 861428-061", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 52, name: "Jordans 1 Retro High OG Defiant SB NYC to Paris CD6578-006", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 53, name: "Air Jordans 1 High 'Satin Black Toe' CD0461-016", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 54, name: "Air Jordans 1 Retro High OG \"Chicago\" 555088-101", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 55, name: "Jordans 1 High 'Fearless' CK5666-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 56, name: "Air Jordans 1 Mid GS \"Light Smoke Grey\"554724-092", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 57, name: "Jordans 1 Retro High \"Homage To Home\" 555088-001", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 58, name: "Air Jordans 1 Retro High OG GS \"Crimson Tint\" 555088-081", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 59, name: "Air Jordans 1 High WMNS \"Tie-Dye\" 822949-106", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 60, name: "Air Jordans 1 High 'UNC to Chicago' CD0461-046", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 61, name: "Air Jordans 1 Retro High OG 'Shattered Backboard 3.0' 555088-028", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 62, name: "Air Jordans 1 Retro High OG BG \"Shadow\" 555088-013", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 63, name: "Air Jordans 1 Retro High OG 'Reverse Shattered Backboard' 555088-113", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 64, name: "Air Jordans 1 Mid \"Banned 2020\" 554724-074", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 65, name: "Air Jordans X League Of Legends World Champion DD1453-001", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 66, name: "Jordans 1 High 'Not For Resale'", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 67, name: "Air Jordans 1 Mid \"Milan\"CV3044-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 68, name: "Air Jordans 1 Mid SE \"Coral Stardust 852542-600", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 69, name: "Air Jordans1 Mid \"Sanded Purple\" 554724-445", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 70, name: "Air Jordans 1 Mid \"Bred Toe\" 5554724-066", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 71, name: "Air Jordans 1 Mid \"Black Cone\" 554724-062", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 72, name: "Air Jordans 1 Mid SE 852542-400", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 73, name: "Air Jordans 1 MID \"Top 3\" 554724-124", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 74, name: "Air Jordans 1 MID SE \"South Beach\"852542-306", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 75, name: "Air Jordans 1 Mid (GS)555112-500", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 76, name: "Air Jordans 1 Mid GS \"Pink Foam\" 555112-601", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 77, name: "Air Jordans 1 Mid SE \"Lakers\" 852542-700", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 78, name: "Air Jordans 1 Mid \"Shattered Backboard\" 554724-058", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 79, name: "Air Jordans 1 Mid GS \"Obsidian\"554725-174", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 80, name: "Air Jordans 1 High 'Court Purple' 555088-501", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 81, name: "Air Jordans 1 Retro High OG \"Bio Hack\" 555088-201", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 82, name: "AIR JORDANS 1 RETRO HIGH OG\"Game Royal\"555088-403", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 83, name: "Air Jordans 1 Retro Hi Pre \"Mushroom\"AH7389-003", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 84, name: "Air Jordans 1 Retro High OG \"Shattered Backboard\" 555088-005", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 85, name: "Air Jordans 1 MID SE \"Pine Green\"852542-301", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 86, name: "Air Jordans 1 Mid SE \"Team Orange\"852542-800", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 87, name: "Air Jordans 1 Retro High OG NRG \"Union – Storm Blue\" BV1300-146", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 88, name: "Air Jordans 1 Mid SE GS \"Ice Cream\"DD1666-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 89, name: "Air Jordans 1 Mid \"UNC 554724-106", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 90, name: "Air Jordans 1 Mid PRM \"Sneakersnstuff 20th anniversary\" CT3443-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 91, name: "Jordans 1 Mid White Black 554724-113", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 92, name: "Air Jordans 1 Mid SE 'Sail Light Blue' DA4666-100", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 93, name: "Air Jordans 1 Mid 'Candy' 554725-083", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 94, name: "Air Jordans 1 Mid \"Lakers Top 3\"852542-005", size: "36-40", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 95, name: "AIR JORDANS 1 HIGH ZOOM \"Racer Blue\" CK6637-104", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 96, name: "Air Jordans 1 Mid \"Multicolor\" 554724-125", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 97, name: "Jordans 1 Mid White Black Light Arctic Pink 555112-103", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 98, name: "Air Jordans 1 Mid \"Chile Red\" 554724-075", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 99, name: "Air Jordans 1 Mid Pink Quartz 555112-603", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 100, name: "Air Jordans 1 Mid White Camo'", size: "36-40", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 101, name: "Air Jordan 3 Retro 'White Cement' 136064-105", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 102, name: "Air Jordan 3 Retro 'Black Cement' 136064-010", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 103, name: "Air Jordan 3 Retro 'Fire Red' 136064-160", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 104, name: "Air Jordan 5 Retro 'Fire Red' 136027-102", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 105, name: "Air Jordan 5 Retro 'Grape' 136027-141", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 106, name: "Air Jordan 5 Retro 'Metallic Black' 136027-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 107, name: "Air Jordan 6 Retro 'Infrared' 384664-123", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 108, name: "Air Jordan 6 Retro 'Carmine' 384664-160", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 109, name: "Air Jordan 6 Retro 'Black Infrared' 384664-025", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 110, name: "Air Jordan 7 Retro 'Bordeaux' 304775-061", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 111, name: "Air Jordan 7 Retro 'Hare' 304775-100", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 112, name: "Air Jordan 8 Retro 'Aqua' 305381-045", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 113, name: "Air Jordan 8 Retro 'Playoffs' 305381-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 114, name: "Air Jordan 9 Retro 'Cool Grey' 302370-104", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 115, name: "Air Jordan 11 Retro 'Concord' 378037-100", size: "40-46", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 116, name: "Air Jordan 11 Retro 'Bred' 378037-010", size: "40-46", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 117, name: "Air Jordan 11 Retro 'Space Jam' 378037-003", size: "40-46", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 118, name: "Air Jordan 11 Retro 'Win Like 82' 378037-106", size: "40-46", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 119, name: "Air Jordan 11 Retro 'Cool Grey' 378037-104", size: "40-46", tipo: "stock", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 120, name: "Air Jordan 12 Retro 'Flu Game' 130690-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 121, name: "Air Jordan 12 Retro 'Taxi' 130690-125", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 122, name: "Air Jordan 12 Retro 'Playoffs' 130690-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 123, name: "Air Jordan 13 Retro 'Bred' 414571-010", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 124, name: "Air Jordan 13 Retro 'He Got Game' 414571-122", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 125, name: "Air Jordan 13 Retro 'Chicago' 414571-104", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 126, name: "Air Jordan 14 Retro 'Last Shot' 487471-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 127, name: "Air Jordan 14 Retro 'Candy Cane' 487471-100", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 128, name: "Air Jordan 15 Retro 'Stealth' 136029-001", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 129, name: "Air Jordan 16 Retro 'Midnight Navy' 136030-141", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 130, name: "Air Jordan 17 Retro 'Copper' 136031-161", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 131, name: "Air Jordan 18 Retro 'White Sport Red' 136032-161", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 132, name: "Air Jordan 1 Low 'Chicago' 553558-612", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 133, name: "Air Jordan 1 Low 'Bred' 553558-061", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 134, name: "Air Jordan 1 Low 'Royal' 553558-007", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 135, name: "Air Jordan 1 Low 'Shadow' 553558-013", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 136, name: "Air Jordan 1 Low 'UNC' 553558-401", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 137, name: "Air Jordan 1 Low 'Travis Scott' CZ1055-001", size: "36-46", tipo: "drop", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 138, name: "Air Jordan 1 Low 'Fragment' CZ1055-100", size: "36-46", tipo: "drop", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 139, name: "Air Jordan 1 Low 'OG Chicago' 553558-612", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 140, name: "Air Jordan 1 Low 'Panda' 553558-163", size: "36-46", tipo: "stock", price_eur: 70, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 141, name: "Air Jordan 4 Retro 'Bred' 308497-060", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 142, name: "Air Jordan 4 Retro 'Military Blue' 308497-104", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 143, name: "Air Jordan 4 Retro 'Fire Red' 308497-160", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 144, name: "Air Jordan 4 Retro 'White Oreo' 308497-100", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 145, name: "Air Jordan 4 Retro 'Travis Scott' CD4487-100", size: "40-46", tipo: "drop", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 146, name: "Air Jordan 4 Retro 'Union LA' DJ5712-001", size: "40-46", tipo: "drop", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 147, name: "Air Jordan 4 Retro 'Off-White' CV9388-100", size: "40-46", tipo: "drop", price_eur: 115, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 148, name: "Air Jordan 4 Retro 'Thunder' 308497-008", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 149, name: "Air Jordan 4 Retro 'Lightning' 308497-117", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."},
        {id: 150, name: "Air Jordan 4 Retro 'Red Thunder' CT8527-016", size: "40-46", tipo: "stock", price_eur: 90, desc: "Estado: Novo. Envio grátis. Caixa STREETMOOD incluída."}
    ];
}

// Garantir que products está disponível globalmente
if (typeof window !== 'undefined') {
    window.products = products;
}
